# Generated by Django 6.1.1 on 2026-09-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('source_type', models.CharField(choices=[('LOCAL', 'Local Filesystem'), ('GITHUB', 'GitHub')], max_length=20, verbose_name='source type')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_sync_status', models.CharField(blank=True, max_length=20, verbose_name='last sync status')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='last sync error')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='last sync at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'documentation source',
                'verbose_name_plural': 'documentation sources',
            },
        ),
        migrations.CreateModel(
            name='DocumentationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documentation/logos/', verbose_name='logo')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='documentation.documentationsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'documentation site',
                'verbose_name_plural': 'documentation sites',
            },
        ),
        migrations.CreateModel(
            name='GitHubDocumentationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, verbose_name='owner')),
                ('repository', models.CharField(max_length=200, verbose_name='repository')),
                ('branch', models.CharField(default='main', max_length=200, verbose_name='branch')),
                ('root_path', models.CharField(default='docs', max_length=500, verbose_name='root path')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='last sync at')),
                ('last_commit_sha', models.CharField(blank=True, max_length=100, verbose_name='last commit sha')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github', to='documentation.documentationsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'GitHub documentation source',
                'verbose_name_plural': 'GitHub documentation sources',
            },
        ),
        migrations.CreateModel(
            name='LocalDocumentationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path', models.CharField(max_length=500, verbose_name='root path')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='documentation.documentationsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'local documentation source',
                'verbose_name_plural': 'local documentation sources',
            },
        ),
        migrations.CreateModel(
            name='DocumentationSearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000, verbose_name='path')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='documentation.documentationsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'documentation search document',
                'verbose_name_plural': 'documentation search documents',
                'ordering': ['path'],
                'constraints': [models.UniqueConstraint(fields=('source', 'path'), name='unique_source_path')],
            },
        ),
    ]
