# Generated by Django 6.1.1 on 2026-09-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('section', 'Section'), ('group', 'Group'), ('page', 'Page')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('path', models.CharField(blank=True, help_text='Relative markdown path without the .md extension (page nodes only).', max_length=1000, verbose_name='page path')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documentation.documentationnode', verbose_name='parent')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='documentation.documentationsite', verbose_name='site')),
            ],
            options={
                'verbose_name': 'documentation node',
                'verbose_name_plural': 'documentation nodes',
                'ordering': ['order', 'id'],
            },
        ),
    ]
