# Generated by Django 6.1.1 on 2026-09-09 16:24

from django.db import migrations, models


def delete_page_nodes(apps, schema_editor):
    DocumentationNode = apps.get_model("documentation", "DocumentationNode")
    DocumentationNode.objects.filter(type="page").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_documentationnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationnode',
            name='path',
            field=models.CharField(blank=True, help_text='Folder path relative to the provider root (section/group nodes).', max_length=1000, verbose_name='folder path'),
        ),
        migrations.AlterField(
            model_name='documentationnode',
            name='type',
            field=models.CharField(choices=[('section', 'Section'), ('group', 'Group')], max_length=20, verbose_name='type'),
        ),
        migrations.RunPython(delete_page_nodes, migrations.RunPython.noop),
    ]
