# Generated by Django 6.1.1 on 2026-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_documentationnode_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationnode',
            name='access',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Public = visible to everyone; Private = signed-in users only.', max_length=20, verbose_name='access'),
        ),
    ]
