# Generated by Django 6.1.1 on 2026-09-10 21:19

import django.db.models.deletion
from django.db import migrations, models
import documentation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_documentationnode_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('token', documentation.fields.EncryptedTextField(blank=True, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'GitHub credential',
                'verbose_name_plural': 'GitHub credentials',
            },
        ),
        migrations.AddField(
            model_name='githubdocumentationsource',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_sources', to='documentation.githubcredential', verbose_name='credential'),
        ),
    ]
