# Generated by Django 6.1.1 on 2026-09-10 07:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_githubcredential_githubdocumentationsource_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Enezadocs', max_length=100, verbose_name='brand name')),
                ('hero_eyebrow', models.CharField(default='Documentation hub', max_length=100, verbose_name='hero eyebrow')),
                ('hero_title', models.CharField(default='Every Eneza product, documented in one place.', max_length=300, verbose_name='hero title')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='hero subtitle')),
                ('cta_title', models.CharField(default="Can't find what you need?", max_length=200, verbose_name='cta title')),
                ('cta_subtitle', models.TextField(blank=True, verbose_name='cta subtitle')),
                ('footer_tagline', models.TextField(blank=True, verbose_name='footer tagline')),
                ('latest_release', models.CharField(default='v1.0', max_length=50, verbose_name='latest release')),
                ('quick_install_title', models.CharField(blank=True, max_length=200, verbose_name='quick install title')),
                ('quick_install_description', models.TextField(blank=True, verbose_name='quick install description')),
                ('quick_install_code', models.TextField(blank=True, verbose_name='quick install code')),
                ('quick_install_bullets', models.TextField(blank=True, help_text='One bullet per line.', verbose_name='quick install bullets')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home page',
            },
        ),
        migrations.AlterModelOptions(
            name='documentationsite',
            options={'ordering': ['order', 'name'], 'verbose_name': 'documentation site', 'verbose_name_plural': 'documentation sites'},
        ),
        migrations.AddField(
            model_name='documentationsite',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='documentationsite',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
        migrations.AddField(
            model_name='documentationsite',
            name='icon',
            field=models.CharField(choices=[('layers', 'Layers'), ('code', 'Code'), ('terminal', 'Terminal'), ('shield', 'Shield'), ('database', 'Database'), ('globe', 'Globe'), ('card', 'Card'), ('box', 'Box')], default='layers', max_length=20, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='documentationsite',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.CreateModel(
            name='FeaturedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('subtitle', models.TextField(blank=True, verbose_name='subtitle')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='documentation.documentationsite', verbose_name='site')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_sites', to='documentation.homepage', verbose_name='home page')),
            ],
            options={
                'verbose_name': 'featured site',
                'verbose_name_plural': 'featured sites',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='documentation.homepage', verbose_name='home page')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='documentation.documentationsite', verbose_name='site')),
            ],
            options={
                'verbose_name': 'home update',
                'verbose_name_plural': 'home updates',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='label')),
                ('query', models.CharField(max_length=200, verbose_name='query')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_paths', to='documentation.homepage', verbose_name='home page')),
            ],
            options={
                'verbose_name': 'quick path',
                'verbose_name_plural': 'quick paths',
                'ordering': ['order', 'id'],
            },
        ),
    ]
