# Generated by Django 6.1.1 on 2026-09-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_homepage_alter_documentationsite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('prefix', models.CharField(help_text='Short, non-secret prefix used to identify the token.', max_length=16, unique=True, verbose_name='prefix')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the token; the raw token is never stored.', max_length=64, unique=True, verbose_name='token hash')),
                ('allow_private', models.BooleanField(default=False, help_text='When enabled, this token may read private content inside its scope.', verbose_name='allow private')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.ForeignKey(blank=True, help_text='Optional group node inside the section; empty grants the whole section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documentation.documentationnode', verbose_name='group')),
                ('section', models.ForeignKey(blank=True, help_text='Optional top-level section node; empty grants the whole site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documentation.documentationnode', verbose_name='section')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tokens', to='documentation.documentationsite', verbose_name='site')),
            ],
            options={
                'verbose_name': 'MCP token',
                'verbose_name_plural': 'MCP tokens',
                'ordering': ['name'],
            },
        ),
    ]
