# Generated by Django 6.1.1 on 2026-09-10 11:38

import documentation.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0008_mcpserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcptoken',
            name='token',
            field=documentation.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted copy of the raw token so an admin can re-copy it.', verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='mcptoken',
            name='token_hash',
            field=models.CharField(help_text='SHA-256 hash of the token; used to authenticate requests.', max_length=64, unique=True, verbose_name='token hash'),
        ),
    ]
