# Generated by Django 6.1.1 on 2026-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0011_homepage_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon (PNG, ICO or SVG). Recommended 32x32 or larger.', null=True, upload_to='documentation/branding/', verbose_name='favicon'),
        ),
    ]
